---
title: "Bruno Kuasney"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# Cientista de Dados
Curitiba/PR

Formado em estatística, apaixonado por AI, programação e dados. Amo o que faço e não me imagino fazendo outra coisa que não ciência de dados e inteligência artificial (esse último mais futuramente). Costumo programar meus tempos ociosos antecipadamente, seja me programando para jogar, para fazer curso, para ficar aleatoriamente pela internet, ir ao cinema, ou um pouco de tudo.

---

## Cientista de Dados

* **Telefone:** (41) 99634-2805
* **E-mail:** bruno.kuasney@gmail.com
* **Linkedin:** [www.linkedin.com/in/bruno-kuasney](www.linkedin.com/in/bruno-kuasney)
* **Github:** BKuasney

---

## Formação

* **Graduação** - Bacharel em Estatística pela UFPR - **[Completo]**
* **Curso** - Hadoop - (Udacity)
* **Curso** - Hadoop with Pig - (Udemy)
* **Curso** - Hadoop with Spark - (Udemy)
* **Curso** - Tensorflow and Google Cloud ML - (Udemy)
* **Curso** - Machine Learning with Python - (Udemy)
* **Curso** - MongoDB (Udemy)
* **Curso em andamento** - Redes Neurais e Deep Learning (Udemy)
* **Curso Futuro** - Deep Learning (Udacity)
* **Curso Futuro** - Reinforcement Learning
* **Curso Futuro** - AI

## Habilidades

###Negócios
* Estatística
* Business Intelligence
* Data Analysis
* Data Science

###Data Science
* R
* Python
* Pig
* Spark
* Map Reduce
* Machine Learning R
* Machine Learning Python
* MongoDB
* Pig
* Klipfolio (DataVis)
* QlikView (DataVis)
* QlikSense (DataVis)
* Tableaut (DataVis)
* DataStudio (DataVis)
* R/Shiny Dashboard (DataVis)
* Ferramentas Office
* Macros Excel (com VBA)
* Postgresql

---

## Informações adicionais

* Prezo pelo máximo de automação possível dos dados e das informações.
* Interesse em estar sempre aprendendo e me desenvolvendo.
* Paixão por dados e informação.
* Criatividade para resolver os mais distintos problemas.
* Entusiasta e amante da tecnologia e AI.

---

## Experência Profissional

#### **Projetos Pessoais**
> Crawler para raspagem de dados e análises automáticas, amarrando todo o processo de obtenção e análises no R.

> Testes de algoritmos e analises de bases obtidas no Kaggle.

> Criação de cursos de estatitística, machine learning e análises utilizando o R.

> Freelances esporádicos em data science utilizando Python + Machine Learning.


#### 2016/Dias Atuais - **Mirum Gency**
> Atualmente trabalhando na área de BI e Data Science. Desenvolvimento de dashboards automatizados para atender tanto ao cliente quanto aos analistas, que utilizam tal dashboard para obter direcionamentos. 
>
>Utilização de linguagens **sql**, **r**, **python** e ferramentas de visualização, como **tableaut**, **Qlikview**, **DataStudio**, **Klipfolio** e **Excel**. Análises referentes aos dados obtidos do **Google Analytics**, **Facebook**, **Adwords**, e bases internas de clientes. Realizando **análises estatísticas** e de **machine learning** para os clientes, como **clusterizações**, **segmentações**, **previsões** e **classificações**, para um melhor entendimento do negócio do cliente e do público atingido pelo cliente.

#### 2015/2016 - **RW1**
> Atuei como consultor de Business Inteliggence, utilizando a ferramenta QlickView. Trabalhando alocado no Terminal de Conteiners de Paranaguá. Elaborando dashbaords na ferramenta com intenção de automatizar todo o processo e substituir planilhas de Excel para paineis eletrônicos em Qlikview.
>
> Realização de projeto interno de Análise de Séries Temporais utilizando o R e integrando tudo ao QlikView.

#### 2013/2015 - **Volvo Trucks do Brasil**
> Estágio na Volvo Trucks, mais especificamente na área de estatística. Analisando taxa de falhas e probabilidade de falhas das peças e componentes do caminhão. Elaboração de relatórios para diretoria sob demanda. Automação via R e via Macro/Excel para os analistas e engenheiros. Centralização dos dados de pós venda para estudos, análises pontuais e dashboard para análises ongoing.

#### 2011/2013 - **Mirum Agency**
> Estágio na área de Business Intelligence (mesma área que atuo nos dias atuais). Elaboração de relatórios excel, tratamento dos dados para análises e elaboração de apresentações para clientes externos.

#### 2010/2011 - **Bosch**
> Trabalho sazonal para projeto específico dentro da Bosch, área de Engenharia Logística. O projeto consistia na padronização das caixas com componentes recebidos pelo aumoxarifado. Para isso, era necessária a tabulação dessa informação e a confiabilidade dos dados.

#### 2008/2009 - **CNH - Case New Holland**
> Atuei como menor aprendiz na New Holland. Sendo menor aprendiz em Eletrônica, onde comecei a pegar gosto por excel, dados e programação. Na época, era realizado trabalhos simples, como soldagem de componentes eletrônicos, avaliação de problemas em placas eletrônicas, programação em componentes eletrônicos e pequenas análises em Excel.

